"""update transaction models

Revision ID: 2485154fe68c
Revises: 37e13b8b0e06
Create Date: 2025-06-23 22:57:37.141295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2485154fe68c'
down_revision: Union[str, Sequence[str], None] = '37e13b8b0e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'user_id')
    # ### end Alembic commands ###
